IPMPROG-2834 /api/v1/discovery/protocols
42ity/fty-discovery-ng pull request #60
Opened 2022-02-21 12:57 UTC by jeffdegott

add 'available' property to the GET /api/v1/admin/discovery/protocols response payload

* manual compatibility backport (2.5.0) from featureimage/IPMPROG-1244-discovery-migration (2.6.0)
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>

2022-02-22 06:16 UTC, eric3873 approved these changes

2022-02-23 13:12 UTC, perrettecl requested changes

2022-02-23 13:12 UTC, perrettecl commented on common/commands.h
> +        pack::String available = FIELD("available"); // enum ["yes", "no", "maybe"]
Use real ENUM

2022-02-24 14:35 UTC, jeffdegott commented on common/commands.h
> +        pack::String available = FIELD("available"); // enum ["yes", "no", "maybe"]
done

2022-02-24 14:35 UTC, jeffdegott commented on common/commands.h
> +        pack::String available = FIELD("available"); // enum ["yes", "no", "maybe"]
> Use real ENUM

done

2022-02-25 08:14 UTC, perrettecl approved these changes

2022-02-25 08:14 UTC, merged